
import java.awt.Image;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Huynh Lam - SE62917
 */
public class ComboboxDemo extends javax.swing.JFrame {

    /**
     * Creates new form ComboboxDemo
     */
    public ComboboxDemo() {
        initComponents();
        loadImageName();
        lbImg.setIcon(resizeImg(iconHaiji));
    }

    // Declare image
    ImageIcon iconHaiji = new ImageIcon("img/Haiji.jpg");
    ImageIcon iconKakeru = new ImageIcon("img/Kakeru.jpg");
    ImageIcon iconNicochan = new ImageIcon("img/Nicochan.jpg");
    ImageIcon iconNira = new ImageIcon("img/Nira.jpg");
    ImageIcon iconYuki = new ImageIcon("img/Yuki.jpg");

    // Load image name to Combo Box List
    private void loadImageName() {
        String imageName[] = {"Haiji", "Kakeru", "Nicochan", "Nira", "Yuki"};
        DefaultComboBoxModel model = new DefaultComboBoxModel(imageName);
        cbxImg.setModel(model);
    }

    // Resize Image
    private ImageIcon resizeImg(ImageIcon icon) {
        Image img = icon.getImage();
        img = img.getScaledInstance(lbImg.getWidth(), lbImg.getHeight(), Image.SCALE_SMOOTH);
        icon = new ImageIcon(img);
        return icon;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxImg = new javax.swing.JComboBox<>();
        lbImg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Combo Box Demo");

        cbxImg.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxImgItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Combo Box Demo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxImg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbImg, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbxImgItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxImgItemStateChanged
        Object selected = cbxImg.getSelectedItem();

        // icon Haiji
        if (selected.toString().equals("Haiji")) {
            lbImg.setIcon(resizeImg(iconHaiji));
        }

        // icon Kakeru
        if (selected.toString().equals("Kakeru")) {
            lbImg.setIcon(resizeImg(iconKakeru));
        }

        // icon Nicochan
        if (selected.toString().equals("Nicochan")) {
            lbImg.setIcon(resizeImg(iconNicochan));
        }

        // icon Nira
        if (selected.toString().equals("Nira")) {
            lbImg.setIcon(resizeImg(iconNira));
        }

        // icon Yuki
        if (selected.toString().equals("Yuki")) {
            lbImg.setIcon(resizeImg(iconYuki));
        }
    }//GEN-LAST:event_cbxImgItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComboboxDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComboboxDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComboboxDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComboboxDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComboboxDemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxImg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbImg;
    // End of variables declaration//GEN-END:variables
}
