/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Huynh Lam - SE62917
 */
public class Calculator extends javax.swing.JFrame {

    int operator = -1; // as same as press Equal button
    double firstNum = 0;
    double secondNum = 0;
    boolean calcu = false;

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    // Display result to txtDisplay
    public void result() {
        float convertNumber = Float.parseFloat("" + firstNum);
        txtDisplay.setText(convertNumber + "");
    }

    // Avoid user type "." at the end of the number
    public float getValue() {
        String value = txtDisplay.getText();
        if (value.endsWith(".")) {
            value = value.replace(".", "");
        }
        return Float.parseFloat(value);
    }

    public void pressNumber(String value) {
        if (calcu) {
            txtDisplay.setText("0");
            calcu = false;
        }

        if (txtDisplay.getText().equals("0")) {
            txtDisplay.setText(value);
        } else {
            txtDisplay.setText(txtDisplay.getText() + value);
        }
    }

    // Process Calculation
    public void calculation() throws Exception {
        if (!calcu) {
            if (operator == -1) { // user hasn't type any number
                firstNum = getValue();
            } else { // user type number to start calculate
                secondNum = getValue();
                switch (operator) {
                    case 1:
                        // Plus
                        firstNum += secondNum;
                        result();
                        break;
                    case 2:
                        // Minus
                        firstNum -= secondNum;
                        result();
                        break;
                    case 3:
                        // Multiply
                        firstNum *= secondNum;
                        result();
                        break;
                    case 4:
                        // Divide
                        if (secondNum == 0) {
                            txtDisplay.setText("Divide by 0.Error!");
                            btnNum0.setEnabled(false);
                            btnNum1.setEnabled(false);
                            btnNum2.setEnabled(false);
                            btnNum3.setEnabled(false);
                            btnNum4.setEnabled(false);
                            btnNum5.setEnabled(false);
                            btnNum6.setEnabled(false);
                            btnNum7.setEnabled(false);
                            btnNum8.setEnabled(false);
                            btnNum9.setEnabled(false);
                            btnOpPlus.setEnabled(false);
                            btnOpMinus.setEnabled(false);
                            btnOpMultiply.setEnabled(false);
                            btnOpDivide.setEnabled(false);
                            btnOpEqual.setEnabled(false);
                        } else {
                            firstNum /= secondNum;
                            result();
                        }
                        break;
                    default:
                        break;
                }
            }
            calcu = true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDisplay = new javax.swing.JTextField();
        btnNum7 = new javax.swing.JButton();
        btnNum8 = new javax.swing.JButton();
        btnNum9 = new javax.swing.JButton();
        btnOpPlus = new javax.swing.JButton();
        btnNum4 = new javax.swing.JButton();
        btnNum5 = new javax.swing.JButton();
        btnNum6 = new javax.swing.JButton();
        btnOpMinus = new javax.swing.JButton();
        btnNum1 = new javax.swing.JButton();
        btnNum2 = new javax.swing.JButton();
        btnNum3 = new javax.swing.JButton();
        btnOpMultiply = new javax.swing.JButton();
        btnNum0 = new javax.swing.JButton();
        btnOpDivide = new javax.swing.JButton();
        btnOpEqual = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simple Calculator");
        setResizable(false);

        txtDisplay.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnNum7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNum7.setText("7");
        btnNum7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNum7.setMaximumSize(new java.awt.Dimension(13, 21));
        btnNum7.setPreferredSize(new java.awt.Dimension(13, 21));
        btnNum7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum7ActionPerformed(evt);
            }
        });

        btnNum8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNum8.setText("8");
        btnNum8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNum8.setMaximumSize(new java.awt.Dimension(13, 21));
        btnNum8.setPreferredSize(new java.awt.Dimension(13, 21));
        btnNum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum8ActionPerformed(evt);
            }
        });

        btnNum9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNum9.setText("9");
        btnNum9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNum9.setMaximumSize(new java.awt.Dimension(13, 21));
        btnNum9.setPreferredSize(new java.awt.Dimension(13, 21));
        btnNum9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum9ActionPerformed(evt);
            }
        });

        btnOpPlus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnOpPlus.setText("+");
        btnOpPlus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnOpPlus.setMaximumSize(new java.awt.Dimension(13, 21));
        btnOpPlus.setPreferredSize(new java.awt.Dimension(13, 21));
        btnOpPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpPlusActionPerformed(evt);
            }
        });

        btnNum4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNum4.setText("4");
        btnNum4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNum4.setMaximumSize(new java.awt.Dimension(13, 21));
        btnNum4.setPreferredSize(new java.awt.Dimension(13, 21));
        btnNum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum4ActionPerformed(evt);
            }
        });

        btnNum5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNum5.setText("5");
        btnNum5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNum5.setMaximumSize(new java.awt.Dimension(13, 21));
        btnNum5.setPreferredSize(new java.awt.Dimension(13, 21));
        btnNum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum5ActionPerformed(evt);
            }
        });

        btnNum6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNum6.setText("6");
        btnNum6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNum6.setMaximumSize(new java.awt.Dimension(13, 21));
        btnNum6.setPreferredSize(new java.awt.Dimension(13, 21));
        btnNum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum6ActionPerformed(evt);
            }
        });

        btnOpMinus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnOpMinus.setText("-");
        btnOpMinus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnOpMinus.setMaximumSize(new java.awt.Dimension(13, 21));
        btnOpMinus.setPreferredSize(new java.awt.Dimension(13, 21));
        btnOpMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpMinusActionPerformed(evt);
            }
        });

        btnNum1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNum1.setText("1");
        btnNum1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNum1.setMaximumSize(new java.awt.Dimension(13, 21));
        btnNum1.setPreferredSize(new java.awt.Dimension(13, 21));
        btnNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum1ActionPerformed(evt);
            }
        });

        btnNum2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNum2.setText("2");
        btnNum2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNum2.setMaximumSize(new java.awt.Dimension(13, 21));
        btnNum2.setPreferredSize(new java.awt.Dimension(13, 21));
        btnNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum2ActionPerformed(evt);
            }
        });

        btnNum3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNum3.setText("3");
        btnNum3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNum3.setMaximumSize(new java.awt.Dimension(13, 21));
        btnNum3.setPreferredSize(new java.awt.Dimension(13, 21));
        btnNum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum3ActionPerformed(evt);
            }
        });

        btnOpMultiply.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnOpMultiply.setText("*");
        btnOpMultiply.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnOpMultiply.setMaximumSize(new java.awt.Dimension(13, 21));
        btnOpMultiply.setPreferredSize(new java.awt.Dimension(13, 21));
        btnOpMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpMultiplyActionPerformed(evt);
            }
        });

        btnNum0.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNum0.setText("0");
        btnNum0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNum0.setMaximumSize(new java.awt.Dimension(13, 21));
        btnNum0.setPreferredSize(new java.awt.Dimension(13, 21));
        btnNum0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum0ActionPerformed(evt);
            }
        });

        btnOpDivide.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnOpDivide.setText("/");
        btnOpDivide.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnOpDivide.setMaximumSize(new java.awt.Dimension(13, 21));
        btnOpDivide.setPreferredSize(new java.awt.Dimension(13, 21));
        btnOpDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpDivideActionPerformed(evt);
            }
        });

        btnOpEqual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnOpEqual.setText("=");
        btnOpEqual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnOpEqual.setMaximumSize(new java.awt.Dimension(13, 21));
        btnOpEqual.setPreferredSize(new java.awt.Dimension(13, 21));
        btnOpEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpEqualActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnClear.setText("Clear");
        btnClear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnClear.setMaximumSize(new java.awt.Dimension(13, 21));
        btnClear.setPreferredSize(new java.awt.Dimension(13, 21));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDisplay)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnOpPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnOpMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnOpEqual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addComponent(btnOpMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(btnOpDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOpEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNum0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum0ActionPerformed
        pressNumber("0");
    }//GEN-LAST:event_btnNum0ActionPerformed

    private void btnNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum1ActionPerformed
        pressNumber("1");
    }//GEN-LAST:event_btnNum1ActionPerformed

    private void btnNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum2ActionPerformed
        pressNumber("2");
    }//GEN-LAST:event_btnNum2ActionPerformed

    private void btnNum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum3ActionPerformed
        pressNumber("3");
    }//GEN-LAST:event_btnNum3ActionPerformed

    private void btnNum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum4ActionPerformed
        pressNumber("4");
    }//GEN-LAST:event_btnNum4ActionPerformed

    private void btnNum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum5ActionPerformed
        pressNumber("5");
    }//GEN-LAST:event_btnNum5ActionPerformed

    private void btnNum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum6ActionPerformed
        pressNumber("6");
    }//GEN-LAST:event_btnNum6ActionPerformed

    private void btnNum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum7ActionPerformed
        pressNumber("7");
    }//GEN-LAST:event_btnNum7ActionPerformed

    private void btnNum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum8ActionPerformed
        pressNumber("8");
    }//GEN-LAST:event_btnNum8ActionPerformed

    private void btnNum9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum9ActionPerformed
        pressNumber("9");
    }//GEN-LAST:event_btnNum9ActionPerformed

    private void btnOpPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpPlusActionPerformed
        try {
            calculation();
        } catch (Exception e) {
            txtDisplay.setText("Math Error");
            e.printStackTrace();
        }

        operator = 1;
    }//GEN-LAST:event_btnOpPlusActionPerformed

    private void btnOpMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpMinusActionPerformed
        try {
            calculation();
        } catch (Exception e) {
            txtDisplay.setText("Math Error");
            e.printStackTrace();
        }

        operator = 2;
    }//GEN-LAST:event_btnOpMinusActionPerformed

    private void btnOpMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpMultiplyActionPerformed
        try {
            calculation();
        } catch (Exception e) {
            txtDisplay.setText("Math Error");
            e.printStackTrace();
        }

        operator = 3;
    }//GEN-LAST:event_btnOpMultiplyActionPerformed

    private void btnOpDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpDivideActionPerformed
        try {
            calculation();
        } catch (Exception e) {
            txtDisplay.setText("Math Error");
            e.printStackTrace();
        }

        operator = 4;
    }//GEN-LAST:event_btnOpDivideActionPerformed

    private void btnOpEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpEqualActionPerformed
        try {
            calculation();
        } catch (Exception e) {
            txtDisplay.setText("Math Error");
            e.printStackTrace();
        }

        operator = -1;
    }//GEN-LAST:event_btnOpEqualActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        btnNum0.setEnabled(true);
        btnNum1.setEnabled(true);
        btnNum2.setEnabled(true);
        btnNum3.setEnabled(true);
        btnNum4.setEnabled(true);
        btnNum5.setEnabled(true);
        btnNum6.setEnabled(true);
        btnNum7.setEnabled(true);
        btnNum8.setEnabled(true);
        btnNum9.setEnabled(true);
        btnOpPlus.setEnabled(true);
        btnOpMinus.setEnabled(true);
        btnOpMultiply.setEnabled(true);
        btnOpDivide.setEnabled(true);
        btnOpEqual.setEnabled(true);
        txtDisplay.setText("0");

        operator = -1;
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnNum0;
    private javax.swing.JButton btnNum1;
    private javax.swing.JButton btnNum2;
    private javax.swing.JButton btnNum3;
    private javax.swing.JButton btnNum4;
    private javax.swing.JButton btnNum5;
    private javax.swing.JButton btnNum6;
    private javax.swing.JButton btnNum7;
    private javax.swing.JButton btnNum8;
    private javax.swing.JButton btnNum9;
    private javax.swing.JButton btnOpDivide;
    private javax.swing.JButton btnOpEqual;
    private javax.swing.JButton btnOpMinus;
    private javax.swing.JButton btnOpMultiply;
    private javax.swing.JButton btnOpPlus;
    private javax.swing.JTextField txtDisplay;
    // End of variables declaration//GEN-END:variables
}
