
import java.awt.Image;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Huynh Lam - SE62917
 */
public class DisplayAndResizeImage extends javax.swing.JFrame {

    /**
     * Creates new form ImageIcon
     */
    public DisplayAndResizeImage() {
        initComponents();
        loadImage();
    }

    // Declare Image Icon
    ImageIcon iconHaiji = new ImageIcon("img/Haiji.jpg");
    ImageIcon iconKakeru = new ImageIcon("img/Kakeru.jpg");
    ImageIcon iconNicochan = new ImageIcon("img/Nicochan.jpg");
    ImageIcon iconNira = new ImageIcon("img/Nira.jpg");
    ImageIcon iconYuki = new ImageIcon("img/Yuki.jpg");

    // Resize Image for label Display
    private ImageIcon resizeImgLabel(ImageIcon icon) {
        Image img = icon.getImage();
        img = img.getScaledInstance(lbDisplayImg.getWidth(), lbDisplayImg.getHeight(), Image.SCALE_SMOOTH);
        icon = new ImageIcon(img);
        return icon;
    }

    // Resize Image for button in toolbar
    private ImageIcon resizeImgToolbar(ImageIcon icon) {
        Image img = icon.getImage();
        img = img.getScaledInstance(btnImg1.getWidth(), btnImg1.getHeight(), Image.SCALE_SMOOTH);
        icon = new ImageIcon(img);
        return icon;
    }

    // Set icon for buttons in toolbar
    private void loadImage() {
        btnImg1.setIcon(resizeImgToolbar(iconHaiji));
        btnImg2.setIcon(resizeImgToolbar(iconKakeru));
        btnImg3.setIcon(resizeImgToolbar(iconNicochan));
        btnImg4.setIcon(resizeImgToolbar(iconNira));
        btnImg5.setIcon(resizeImgToolbar(iconYuki));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbDisplayImg = new javax.swing.JLabel();
        tbrImg = new javax.swing.JToolBar();
        btnImg1 = new javax.swing.JButton();
        btnImg2 = new javax.swing.JButton();
        btnImg3 = new javax.swing.JButton();
        btnImg4 = new javax.swing.JButton();
        btnImg5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Display and resize an image");

        tbrImg.setRollover(true);

        btnImg1.setFocusable(false);
        btnImg1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImg1.setMaximumSize(new java.awt.Dimension(100, 100));
        btnImg1.setMinimumSize(new java.awt.Dimension(100, 100));
        btnImg1.setPreferredSize(new java.awt.Dimension(100, 100));
        btnImg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImg1ActionPerformed(evt);
            }
        });
        tbrImg.add(btnImg1);

        btnImg2.setFocusable(false);
        btnImg2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImg2.setMaximumSize(new java.awt.Dimension(100, 100));
        btnImg2.setMinimumSize(new java.awt.Dimension(100, 100));
        btnImg2.setPreferredSize(new java.awt.Dimension(100, 100));
        btnImg2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnImg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImg2ActionPerformed(evt);
            }
        });
        tbrImg.add(btnImg2);

        btnImg3.setFocusable(false);
        btnImg3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImg3.setMaximumSize(new java.awt.Dimension(100, 100));
        btnImg3.setMinimumSize(new java.awt.Dimension(100, 100));
        btnImg3.setPreferredSize(new java.awt.Dimension(100, 100));
        btnImg3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnImg3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImg3ActionPerformed(evt);
            }
        });
        tbrImg.add(btnImg3);

        btnImg4.setFocusable(false);
        btnImg4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImg4.setMaximumSize(new java.awt.Dimension(100, 100));
        btnImg4.setMinimumSize(new java.awt.Dimension(100, 100));
        btnImg4.setPreferredSize(new java.awt.Dimension(100, 100));
        btnImg4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnImg4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImg4ActionPerformed(evt);
            }
        });
        tbrImg.add(btnImg4);

        btnImg5.setFocusable(false);
        btnImg5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImg5.setMaximumSize(new java.awt.Dimension(100, 100));
        btnImg5.setMinimumSize(new java.awt.Dimension(100, 100));
        btnImg5.setPreferredSize(new java.awt.Dimension(100, 100));
        btnImg5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnImg5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImg5ActionPerformed(evt);
            }
        });
        tbrImg.add(btnImg5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tbrImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbDisplayImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbDisplayImg, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tbrImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnImg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImg1ActionPerformed
        //ImageIcon icon = (ImageIcon) btnImg1.getIcon();
        lbDisplayImg.setIcon(resizeImgLabel(iconHaiji));
    }//GEN-LAST:event_btnImg1ActionPerformed

    private void btnImg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImg2ActionPerformed
        //ImageIcon icon = (ImageIcon) btnImg2.getIcon();
        lbDisplayImg.setIcon(resizeImgLabel(iconKakeru));
    }//GEN-LAST:event_btnImg2ActionPerformed

    private void btnImg3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImg3ActionPerformed
        //ImageIcon icon = (ImageIcon) btnImg3.getIcon();
        lbDisplayImg.setIcon(resizeImgLabel(iconNicochan));
    }//GEN-LAST:event_btnImg3ActionPerformed

    private void btnImg4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImg4ActionPerformed
        //ImageIcon icon = (ImageIcon) btnImg4.getIcon();
        lbDisplayImg.setIcon(resizeImgLabel(iconNira));
    }//GEN-LAST:event_btnImg4ActionPerformed

    private void btnImg5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImg5ActionPerformed
        //ImageIcon icon = (ImageIcon) btnImg5.getIcon();
        lbDisplayImg.setIcon(resizeImgLabel(iconYuki));
    }//GEN-LAST:event_btnImg5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayAndResizeImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayAndResizeImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayAndResizeImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayAndResizeImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayAndResizeImage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImg1;
    private javax.swing.JButton btnImg2;
    private javax.swing.JButton btnImg3;
    private javax.swing.JButton btnImg4;
    private javax.swing.JButton btnImg5;
    private javax.swing.JLabel lbDisplayImg;
    private javax.swing.JToolBar tbrImg;
    // End of variables declaration//GEN-END:variables
}
